//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing
    {
        public int billing_id { get; set; }
        public int customer_id { get; set; }
        public string bill_amount { get; set; }
        public string quantity { get; set; }
        public int price_id { get; set; }
        public string service_type { get; set; }
        public string status { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
