//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection_register
    {
        public int id { get; set; }
        public string Guest_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> collection_date { get; set; }
        public Nullable<System.DateTime> proposed_delivery_date { get; set; }
        public string delivery_personel { get; set; }
        public Nullable<int> cloth_quantity { get; set; }
        public string Description { get; set; }
        public string ServiceType { get; set; }
        public string guest_phone { get; set; }
        public string guest_number { get; set; }
        public string guest_email { get; set; }
        public string guest_room_number { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string Emp_name { get; set; }
        public Nullable<int> emp_number { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> hotel_guest_id { get; set; }
        public Nullable<int> Reservation_id { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual Hotel_reservation Hotel_reservation { get; set; }
        public virtual Hotel_Room Hotel_Room { get; set; }
        public virtual Hotel_guest Hotel_guest { get; set; }
    }
}
