//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelDBEntities : DbContext
    {
        public HotelDBEntities()
            : base("name=HotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_hrm_employee> admin_hrm_employee { get; set; }
        public virtual DbSet<Hotel_AddOns> Hotel_AddOns { get; set; }
        public virtual DbSet<Hotel_amenity> Hotel_amenity { get; set; }
        public virtual DbSet<Hotel_Booking_status> Hotel_Booking_status { get; set; }
        public virtual DbSet<Hotel_Hotel_Information> Hotel_Hotel_Information { get; set; }
        public virtual DbSet<Hotel_PaymentOption> Hotel_PaymentOption { get; set; }
        public virtual DbSet<Hotel_Payments> Hotel_Payments { get; set; }
        public virtual DbSet<Hotel_promo> Hotel_promo { get; set; }
        public virtual DbSet<Hotel_reservation> Hotel_reservation { get; set; }
        public virtual DbSet<Hotel_ReservationAddon> Hotel_ReservationAddon { get; set; }
        public virtual DbSet<Hotel_ReservationPayment> Hotel_ReservationPayment { get; set; }
        public virtual DbSet<Hotel_ReservationType> Hotel_ReservationType { get; set; }
        public virtual DbSet<Hotel_Room_Type> Hotel_Room_Type { get; set; }
        public virtual DbSet<HotelEmployee> HotelEmployees { get; set; }
        public virtual DbSet<ws_lookup> ws_lookup { get; set; }
        public virtual DbSet<ws_notification> ws_notification { get; set; }
        public virtual DbSet<billing> billings { get; set; }
        public virtual DbSet<delivery> deliveries { get; set; }
        public virtual DbSet<pricing> pricings { get; set; }
        public virtual DbSet<Laundry_admin> Laundry_admin { get; set; }
        public virtual DbSet<product_admin> product_admin { get; set; }
        public virtual DbSet<collection_register> collection_register { get; set; }
        public virtual DbSet<entry_information> entry_information { get; set; }
        public virtual DbSet<Hotel_Room> Hotel_Room { get; set; }
        public virtual DbSet<Hotel_booking_admin> Hotel_booking_admin { get; set; }
        public virtual DbSet<Hotel_guest> Hotel_guest { get; set; }
    }
}
