//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public int id { get; set; }
        public string emp_name { get; set; }
        public string Guest_name { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.DateTime> finished_date { get; set; }
        public string price { get; set; }
        public string Guest_room_number { get; set; }
        public string Guest_number { get; set; }
        public string Clothe_description { get; set; }
        public Nullable<int> Deleted { get; set; }
        public string Total_price { get; set; }
    }
}
