//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_ReservationAddon
    {
        public int Id { get; set; }
        public Nullable<int> addon_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> reservation_id { get; set; }
        public string description { get; set; }
    
        public virtual Hotel_AddOns Hotel_AddOns { get; set; }
        public virtual Hotel_reservation Hotel_reservation { get; set; }
        public virtual Hotel_Room Hotel_Room { get; set; }
    }
}
