//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel_reservation()
        {
            this.Hotel_ReservationAddon = new HashSet<Hotel_ReservationAddon>();
            this.collection_register = new HashSet<collection_register>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Room_id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<System.DateTime> reservation_date { get; set; }
        public Nullable<int> reservation_status { get; set; }
        public string reservation_comment { get; set; }
        public Nullable<System.DateTime> reservation_checking_date { get; set; }
        public Nullable<System.DateTime> reservation_checkout_date { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> reservation_typeId { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<int> payment_option { get; set; }
        public Nullable<int> paymentTypeId { get; set; }
        public Nullable<int> payment_status { get; set; }
        public string session { get; set; }
    
        public virtual Hotel_PaymentOption Hotel_PaymentOption { get; set; }
        public virtual Hotel_ReservationType Hotel_ReservationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_ReservationAddon> Hotel_ReservationAddon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<collection_register> collection_register { get; set; }
        public virtual Hotel_Room Hotel_Room { get; set; }
        public virtual Hotel_guest Hotel_guest { get; set; }
    }
}
