//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_AddOns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel_AddOns()
        {
            this.Hotel_ReservationAddon = new HashSet<Hotel_ReservationAddon>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Hotel_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<int> promo_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> deleted { get; set; }
    
        public virtual Hotel_Hotel_Information Hotel_Hotel_Information { get; set; }
        public virtual Hotel_promo Hotel_promo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_ReservationAddon> Hotel_ReservationAddon { get; set; }
    }
}
