//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel_Room()
        {
            this.collection_register = new HashSet<collection_register>();
            this.Hotel_amenity = new HashSet<Hotel_amenity>();
            this.Hotel_reservation = new HashSet<Hotel_reservation>();
            this.Hotel_ReservationAddon = new HashSet<Hotel_ReservationAddon>();
        }
    
        public int Id { get; set; }
        public string Room_number { get; set; }
        public Nullable<int> Hotel_id { get; set; }
        public Nullable<int> Location_id { get; set; }
        public string room_type { get; set; }
        public Nullable<int> room_typeid { get; set; }
        public string room_category { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> promo_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string RoomImage1 { get; set; }
        public string RoomImage2 { get; set; }
        public string RoomImage3 { get; set; }
        public string RoomImage4 { get; set; }
        public string RoomImage5 { get; set; }
        public string Room_Description { get; set; }
        public Nullable<int> max_children { get; set; }
        public Nullable<int> max_adults { get; set; }
        public Nullable<int> max_people { get; set; }
        public Nullable<int> min_people { get; set; }
        public Nullable<int> start_lock { get; set; }
        public Nullable<int> end_lock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<collection_register> collection_register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_amenity> Hotel_amenity { get; set; }
        public virtual Hotel_promo Hotel_promo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_reservation> Hotel_reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_ReservationAddon> Hotel_ReservationAddon { get; set; }
        public virtual Hotel_Room_Type Hotel_Room_Type { get; set; }
    }
}
