//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_Payments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel_Payments()
        {
            this.Hotel_ReservationPayment = new HashSet<Hotel_ReservationPayment>();
        }
    
        public int Id { get; set; }
        public string payments_type { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string description { get; set; }
        public string Payment_for { get; set; }
        public string PaymentBy { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> ReservationId { get; set; }
    
        public virtual Hotel_PaymentOption Hotel_PaymentOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_ReservationPayment> Hotel_ReservationPayment { get; set; }
    }
}
