//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_ReservationPayment
    {
        public int Id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Hotel_Payments Hotel_Payments { get; set; }
        public virtual Hotel_ReservationPayment Hotel_ReservationPayment1 { get; set; }
        public virtual Hotel_ReservationPayment Hotel_ReservationPayment2 { get; set; }
    }
}
