//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel_guest()
        {
            this.collection_register = new HashSet<collection_register>();
            this.Hotel_reservation = new HashSet<Hotel_reservation>();
        }
    
        public int Id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Other_names { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Nextofkin_fullname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Nextofkin_fulladdress { get; set; }
        public string Nextofkin_phonenumber { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> deleted { get; set; }
        public string Phone_number { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> LastDiscountAmount { get; set; }
        public Nullable<int> LastDiscountPercentage { get; set; }
        public string DiscountapprovedBy { get; set; }
        public string EmailOfDiscountapprovedPerson { get; set; }
        public Nullable<int> emp_number { get; set; }
        public Nullable<System.DateTime> DateOfLastDiscountUpdate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<collection_register> collection_register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_reservation> Hotel_reservation { get; set; }
    }
}
