//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_ReservationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel_ReservationType()
        {
            this.Hotel_reservation = new HashSet<Hotel_reservation>();
        }
    
        public int Id { get; set; }
        public string Type_name { get; set; }
        public string Type_description { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_reservation> Hotel_reservation { get; set; }
    }
}
