//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_amenity
    {
        public int Id { get; set; }
        public Nullable<int> room_id { get; set; }
        public string amenity_name { get; set; }
        public string amenity_category { get; set; }
        public Nullable<int> amenity_status { get; set; }
        public string amenity_description { get; set; }
    
        public virtual Hotel_Room Hotel_Room { get; set; }
    }
}
