//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laundry_admin
    {
        public int Id { get; set; }
        public Nullable<int> emp_number { get; set; }
        public Nullable<int> laundry_id { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
    }
}
