//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_lookup
    {
        public int id { get; set; }
        public string lookup_name { get; set; }
        public Nullable<int> orderd { get; set; }
        public string category { get; set; }
        public Nullable<int> deleted { get; set; }
    }
}
