//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_notification
    {
        public System.Guid id { get; set; }
        public int emp_number { get; set; }
        public string message { get; set; }
        public System.DateTime created_at { get; set; }
        public int viewed { get; set; }
        public string link { get; set; }
    }
}
