//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin_hrm_employee()
        {
            this.bpm_workflow_employee = new HashSet<bpm_workflow_employee>();
            this.bpm_vendor_document = new HashSet<bpm_vendor_document>();
            this.bpm_workflow = new HashSet<bpm_workflow>();
            this.bpm_process = new HashSet<bpm_process>();
            this.bpm_process1 = new HashSet<bpm_process>();
        }
    
        public int emp_number { get; set; }
        public string employee_id { get; set; }
        public string emp_lastname { get; set; }
        public string emp_firstname { get; set; }
        public string emp_middle_name { get; set; }
        public string emp_nick_name { get; set; }
        public string ethnic_race_code { get; set; }
        public Nullable<System.DateTime> emp_birthday { get; set; }
        public Nullable<int> nation_code { get; set; }
        public Nullable<byte> emp_gender { get; set; }
        public string emp_marital_status { get; set; }
        public string emp_ssn_num { get; set; }
        public string emp_sin_num { get; set; }
        public string emp_other_id { get; set; }
        public string emp_dri_lice_num { get; set; }
        public Nullable<System.DateTime> emp_dri_lice_exp_date { get; set; }
        public string emp_military_service { get; set; }
        public Nullable<int> emp_status { get; set; }
        public Nullable<int> job_title_code { get; set; }
        public Nullable<int> eeo_cat_code { get; set; }
        public Nullable<int> work_station { get; set; }
        public string emp_street1 { get; set; }
        public string emp_street2 { get; set; }
        public string city_code { get; set; }
        public string coun_code { get; set; }
        public string provin_code { get; set; }
        public string emp_zipcode { get; set; }
        public string emp_hm_telephone { get; set; }
        public string emp_mobile { get; set; }
        public string emp_work_telephone { get; set; }
        public string emp_work_email { get; set; }
        public string sal_grd_code { get; set; }
        public Nullable<System.DateTime> joined_date { get; set; }
        public string emp_oth_email { get; set; }
        public Nullable<int> termination_id { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string emp_about { get; set; }
        public string user_id { get; set; }
        public Nullable<int> active { get; set; }
        public int deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_workflow_employee> bpm_workflow_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_vendor_document> bpm_vendor_document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_workflow> bpm_workflow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_process> bpm_process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_process> bpm_process1 { get; set; }
    }
}
