//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bpm_lnk_vendor_category
    {
        public int id { get; set; }
        public int vendor_id { get; set; }
        public int category_id { get; set; }
    
        public virtual bpm_vendor_category bpm_vendor_category { get; set; }
        public virtual bpm_vendor bpm_vendor { get; set; }
    }
}
