//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bpm_vendor_document
    {
        public System.Guid id { get; set; }
        public int vendor_id { get; set; }
        public int description { get; set; }
        public string file_path { get; set; }
        public System.DateTime created_at { get; set; }
        public int created_by { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual ws_lookup ws_lookup { get; set; }
        public virtual bpm_vendor bpm_vendor { get; set; }
    }
}
