//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bpm_workflow_program_approval
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public int emp_number { get; set; }
        public int job_title { get; set; }
    }
}
