//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bpm_vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bpm_vendor()
        {
            this.bpm_lnk_vendor_category = new HashSet<bpm_lnk_vendor_category>();
            this.bpm_vendor_document = new HashSet<bpm_vendor_document>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string company_name { get; set; }
        public string address { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Lga { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int deleted { get; set; }
        public string tin { get; set; }
        public string account_number { get; set; }
        public string bank_name { get; set; }
        public string account_name { get; set; }
        public string rc_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_lnk_vendor_category> bpm_lnk_vendor_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_vendor_document> bpm_vendor_document { get; set; }
    }
}
