//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bpm_workflow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bpm_workflow()
        {
            this.bpm_transaction_token = new HashSet<bpm_transaction_token>();
            this.bpm_workflow_employee = new HashSet<bpm_workflow_employee>();
            this.bpm_payments = new HashSet<bpm_payments>();
            this.bpm_payments1 = new HashSet<bpm_payments>();
            this.bpm_workflow_document = new HashSet<bpm_workflow_document>();
        }
    
        public System.Guid id { get; set; }
        public string workflow { get; set; }
        public System.DateTime created_at { get; set; }
        public int created_by { get; set; }
        public int status { get; set; }
        public System.Guid process_id { get; set; }
        public int project_id { get; set; }
        public string title { get; set; }
        public int deleted { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_transaction_token> bpm_transaction_token { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_workflow_employee> bpm_workflow_employee { get; set; }
        public virtual pm_project pm_project { get; set; }
        public virtual ws_lookup ws_lookup { get; set; }
        public virtual bpm_process bpm_process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_payments> bpm_payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_payments> bpm_payments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bpm_workflow_document> bpm_workflow_document { get; set; }
    }
}
