//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow.DAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class workFlowEntities : DbContext
    {
        public workFlowEntities()
            : base("name=workFlowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_hrm_employee> admin_hrm_employee { get; set; }
        public virtual DbSet<bpm_form_design> bpm_form_design { get; set; }
        public virtual DbSet<pm_project> pm_project { get; set; }
        public virtual DbSet<bpm_workflow_employee> bpm_workflow_employee { get; set; }
        public virtual DbSet<bpm_vendor_document> bpm_vendor_document { get; set; }
        public virtual DbSet<ws_lookup> ws_lookup { get; set; }
        public virtual DbSet<bpm_link_travel_expense> bpm_link_travel_expense { get; set; }
        public virtual DbSet<bpm_travel_expenses> bpm_travel_expenses { get; set; }
        public virtual DbSet<bpm_travel_type> bpm_travel_type { get; set; }
        public virtual DbSet<bpm_lnk_vendor_category> bpm_lnk_vendor_category { get; set; }
        public virtual DbSet<bpm_transaction_token> bpm_transaction_token { get; set; }
        public virtual DbSet<bpm_vendor_category> bpm_vendor_category { get; set; }
        public virtual DbSet<bpm_vendor> bpm_vendor { get; set; }
        public virtual DbSet<bpm_approval_token> bpm_approval_token { get; set; }
        public virtual DbSet<bpm_workflow> bpm_workflow { get; set; }
        public virtual DbSet<bpm_item> bpm_item { get; set; }
        public virtual DbSet<bpm_process> bpm_process { get; set; }
        public virtual DbSet<bpm_payments> bpm_payments { get; set; }
        public virtual DbSet<bpm_workflow_program_approval> bpm_workflow_program_approval { get; set; }
        public virtual DbSet<bpm_workflow_document> bpm_workflow_document { get; set; }
    }
}
