//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public int AddressType_AddressTypeID { get; set; }
        public string StreetAddress { get; set; }
        public int CityZip_CityZipID { get; set; }
        public int Guest_GuestID { get; set; }
        public int Hotel_HotelID { get; set; }
        public Nullable<int> Employee_EmployeeNumber { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
