//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_emp_dependents
    {
        public int emp_number { get; set; }
        public decimal ed_seqno { get; set; }
        public string ed_name { get; set; }
        public string ed_relationship_type { get; set; }
        public string ed_relationship { get; set; }
        public Nullable<System.DateTime> ed_date_of_birth { get; set; }
        public Nullable<int> ed_nation_code { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
    }
}
