//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_leave
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> length_hours { get; set; }
        public Nullable<decimal> length_days { get; set; }
        public Nullable<int> status { get; set; }
        public string comments { get; set; }
        public int leave_request_id { get; set; }
        public int leave_type_id { get; set; }
        public int emp_number { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual admin_hrm_leave_request admin_hrm_leave_request { get; set; }
        public virtual admin_hrm_leave_status admin_hrm_leave_status { get; set; }
        public virtual admin_hrm_leave_type admin_hrm_leave_type { get; set; }
    }
}
