//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin_hrm_activity()
        {
            this.admin_hrm_timesheet_item = new HashSet<admin_hrm_timesheet_item>();
            this.admin_hrm_timesheet_lk_project_activity = new HashSet<admin_hrm_timesheet_lk_project_activity>();
        }
    
        public int id { get; set; }
        public string activity_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_timesheet_item> admin_hrm_timesheet_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_timesheet_lk_project_activity> admin_hrm_timesheet_lk_project_activity { get; set; }
    }
}
