//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_suggestion_files
    {
        public int Id { get; set; }
        public Nullable<int> suggestion_id { get; set; }
        public string filename { get; set; }
    
        public virtual admin_hrm_suggestion admin_hrm_suggestion { get; set; }
    }
}
