//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_lk_directorate_subunit
    {
        public int id { get; set; }
        public int directorate_id { get; set; }
        public int subunit_id { get; set; }
    
        public virtual admin_hrm_directorate admin_hrm_directorate { get; set; }
        public virtual admin_hrm_lkup_subunit admin_hrm_lkup_subunit { get; set; }
    }
}
