//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_emp_job_record_history
    {
        public int employee_number { get; set; }
        public Nullable<int> job_title_id { get; set; }
        public Nullable<int> employment_status_id { get; set; }
        public string employment_status_name { get; set; }
        public Nullable<int> job_category_id { get; set; }
        public string job_category_name { get; set; }
        public Nullable<System.DateTime> joined_date { get; set; }
        public Nullable<System.DateTime> probation_end_date { get; set; }
        public Nullable<System.DateTime> date_of_permanency { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string event_name { get; set; }
        public Nullable<int> subunit_id { get; set; }
        public string subunit_name { get; set; }
        public Nullable<int> location_id { get; set; }
        public string location_name { get; set; }
        public string comment { get; set; }
        public Nullable<byte> has_contract_details { get; set; }
        public Nullable<System.DateTime> contract_start_date { get; set; }
        public Nullable<System.DateTime> contract_end_date { get; set; }
        public string contract_details { get; set; }
        public string contracted_hours { get; set; }
        public Nullable<int> work_shift_id { get; set; }
        public string work_shift_name { get; set; }
        public int version { get; set; }
        public Nullable<System.DateTime> modified_time { get; set; }
        public Nullable<int> modified_by_id { get; set; }
        public string modified_by_name { get; set; }
        public byte deleted { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual admin_hrm_employee admin_hrm_employee1 { get; set; }
        public virtual admin_hrm_lkup_job_title admin_hrm_lkup_job_title { get; set; }
    }
}
