//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_leave_entitlement
    {
        public int id { get; set; }
        public Nullable<int> emp_number { get; set; }
        public decimal no_of_days { get; set; }
        public decimal days_used { get; set; }
        public int leave_type_id { get; set; }
        public System.DateTime from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public Nullable<System.DateTime> credited_date { get; set; }
        public string note { get; set; }
        public int entitlement_type { get; set; }
        public int deleted { get; set; }
        public Nullable<int> created_by_id { get; set; }
        public string created_by_name { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual admin_hrm_leave_entitlement_type admin_hrm_leave_entitlement_type { get; set; }
        public virtual admin_hrm_leave_type admin_hrm_leave_type { get; set; }
    }
}
