//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_leave_request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin_hrm_leave_request()
        {
            this.admin_hrm_leave = new HashSet<admin_hrm_leave>();
            this.admin_hrm_leave_request_comment = new HashSet<admin_hrm_leave_request_comment>();
        }
    
        public int id { get; set; }
        public int leave_type_id { get; set; }
        public System.DateTime leave_start_date { get; set; }
        public System.DateTime date_applied { get; set; }
        public int emp_number { get; set; }
        public string comments { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_leave> admin_hrm_leave { get; set; }
        public virtual admin_hrm_leave_type admin_hrm_leave_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_leave_request_comment> admin_hrm_leave_request_comment { get; set; }
    }
}
