//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_suggestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin_hrm_suggestion()
        {
            this.admin_hrm_suggestion_files = new HashSet<admin_hrm_suggestion_files>();
        }
    
        public int suggestion_id { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> emp_number { get; set; }
        public Nullable<int> Job_title_id { get; set; }
        public string title { get; set; }
        public string user_id { get; set; }
        public Nullable<int> deleted { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual admin_hrm_lkup_job_title admin_hrm_lkup_job_title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_suggestion_files> admin_hrm_suggestion_files { get; set; }
    }
}
