//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_lkup_job_title
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin_hrm_lkup_job_title()
        {
            this.admin_hrm_emp_job_record = new HashSet<admin_hrm_emp_job_record>();
            this.admin_hrm_emp_job_record_history = new HashSet<admin_hrm_emp_job_record_history>();
            this.admin_hrm_suggestion = new HashSet<admin_hrm_suggestion>();
        }
    
        public int id { get; set; }
        public string job_title { get; set; }
        public string job_description { get; set; }
        public string note { get; set; }
        public Nullable<byte> is_deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_job_record> admin_hrm_emp_job_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_job_record_history> admin_hrm_emp_job_record_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_suggestion> admin_hrm_suggestion { get; set; }
    }
}
