//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_emp_work_experience
    {
        public int emp_number { get; set; }
        public decimal eexp_seqno { get; set; }
        public string eexp_employer { get; set; }
        public string eexp_jobtit { get; set; }
        public Nullable<System.DateTime> eexp_from_date { get; set; }
        public Nullable<System.DateTime> eexp_to_date { get; set; }
        public string eexp_comments { get; set; }
        public Nullable<int> eexp_internal { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
    }
}
