//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_timesheet_item
    {
        public int timesheet_item_id { get; set; }
        public int timesheet_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> duration { get; set; }
        public string comment { get; set; }
        public int project_id { get; set; }
        public int emp_number { get; set; }
        public int activity_id { get; set; }
    
        public virtual admin_hrm_activity admin_hrm_activity { get; set; }
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual admin_hrm_timesheet admin_hrm_timesheet { get; set; }
        public virtual pm_project pm_project { get; set; }
    }
}
