//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin_hrm_location()
        {
            this.admin_hrm_emp_locations = new HashSet<admin_hrm_emp_locations>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string country_code { get; set; }
        public string time_zone { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string zip_code { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_locations> admin_hrm_emp_locations { get; set; }
    }
}
