//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin_hrm_employee()
        {
            this.admin_announcement = new HashSet<admin_announcement>();
            this.admin_hrm_emp_basicsalary = new HashSet<admin_hrm_emp_basicsalary>();
            this.admin_hrm_emp_dependents = new HashSet<admin_hrm_emp_dependents>();
            this.admin_hrm_emp_education = new HashSet<admin_hrm_emp_education>();
            this.admin_hrm_emp_emergency_contacts = new HashSet<admin_hrm_emp_emergency_contacts>();
            this.admin_hrm_emp_file = new HashSet<admin_hrm_emp_file>();
            this.admin_hrm_emp_job_record_history = new HashSet<admin_hrm_emp_job_record_history>();
            this.admin_hrm_emp_job_record_history1 = new HashSet<admin_hrm_emp_job_record_history>();
            this.admin_hrm_emp_language = new HashSet<admin_hrm_emp_language>();
            this.admin_hrm_emp_locations = new HashSet<admin_hrm_emp_locations>();
            this.admin_hrm_emp_member_detail = new HashSet<admin_hrm_emp_member_detail>();
            this.admin_hrm_emp_reportto = new HashSet<admin_hrm_emp_reportto>();
            this.admin_hrm_emp_reportto1 = new HashSet<admin_hrm_emp_reportto>();
            this.admin_hrm_emp_skill = new HashSet<admin_hrm_emp_skill>();
            this.admin_hrm_emp_work_experience = new HashSet<admin_hrm_emp_work_experience>();
            this.admin_hrm_leave = new HashSet<admin_hrm_leave>();
            this.admin_hrm_leave_entitlement = new HashSet<admin_hrm_leave_entitlement>();
            this.admin_hrm_leave_request = new HashSet<admin_hrm_leave_request>();
            this.admin_hrm_suggestion_admin = new HashSet<admin_hrm_suggestion_admin>();
            this.admin_hrm_suggestion = new HashSet<admin_hrm_suggestion>();
            this.admin_hrm_timesheet_action_log = new HashSet<admin_hrm_timesheet_action_log>();
            this.admin_hrm_timesheet = new HashSet<admin_hrm_timesheet>();
            this.admin_hrm_timesheet_item = new HashSet<admin_hrm_timesheet_item>();
            this.pm_activity_admin = new HashSet<pm_activity_admin>();
            this.pm_activity_budget = new HashSet<pm_activity_budget>();
            this.pm_activity_budget1 = new HashSet<pm_activity_budget>();
            this.pm_activity_deliverables = new HashSet<pm_activity_deliverables>();
            this.pm_activity_deliverables1 = new HashSet<pm_activity_deliverables>();
            this.pm_activity_files = new HashSet<pm_activity_files>();
            this.pm_activity_files1 = new HashSet<pm_activity_files>();
            this.pm_objective_admin = new HashSet<pm_objective_admin>();
            this.pm_objective_deliverables = new HashSet<pm_objective_deliverables>();
            this.pm_objective_deliverables1 = new HashSet<pm_objective_deliverables>();
            this.pm_objective_files = new HashSet<pm_objective_files>();
            this.pm_objective_files1 = new HashSet<pm_objective_files>();
            this.pm_project_admin = new HashSet<pm_project_admin>();
            this.pm_project_deliverables = new HashSet<pm_project_deliverables>();
            this.pm_project_deliverables1 = new HashSet<pm_project_deliverables>();
            this.pm_project_files = new HashSet<pm_project_files>();
            this.pm_project_files1 = new HashSet<pm_project_files>();
            this.pm_task_admin = new HashSet<pm_task_admin>();
            this.pm_task_deliverables = new HashSet<pm_task_deliverables>();
            this.pm_task_deliverables1 = new HashSet<pm_task_deliverables>();
            this.pm_task_files = new HashSet<pm_task_files>();
            this.pm_task_files1 = new HashSet<pm_task_files>();
            this.ws_complain_admin = new HashSet<ws_complain_admin>();
            this.ws_notification = new HashSet<ws_notification>();
            this.product_admin = new HashSet<product_admin>();
            this.Addresses = new HashSet<Address>();
            this.Overrides = new HashSet<Override>();
            this.Phones = new HashSet<Phone>();
            this.Hotels = new HashSet<Hotel>();
            this.User_Email = new HashSet<User_Email>();
            this.collection_register = new HashSet<collection_register>();
            this.Guests = new HashSet<Guest>();
        }
    
        public int emp_number { get; set; }
        public string employee_id { get; set; }
        public string emp_lastname { get; set; }
        public string emp_firstname { get; set; }
        public string emp_middle_name { get; set; }
        public string emp_nick_name { get; set; }
        public string ethnic_race_code { get; set; }
        public Nullable<System.DateTime> emp_birthday { get; set; }
        public Nullable<int> nation_code { get; set; }
        public Nullable<byte> emp_gender { get; set; }
        public string emp_marital_status { get; set; }
        public string emp_ssn_num { get; set; }
        public string emp_sin_num { get; set; }
        public string emp_other_id { get; set; }
        public string emp_dri_lice_num { get; set; }
        public Nullable<System.DateTime> emp_dri_lice_exp_date { get; set; }
        public string emp_military_service { get; set; }
        public Nullable<int> emp_status { get; set; }
        public Nullable<int> job_title_code { get; set; }
        public Nullable<int> eeo_cat_code { get; set; }
        public Nullable<int> work_station { get; set; }
        public string emp_street1 { get; set; }
        public string emp_street2 { get; set; }
        public string city_code { get; set; }
        public string coun_code { get; set; }
        public string provin_code { get; set; }
        public string emp_zipcode { get; set; }
        public string emp_hm_telephone { get; set; }
        public string emp_mobile { get; set; }
        public string emp_work_telephone { get; set; }
        public string emp_work_email { get; set; }
        public string sal_grd_code { get; set; }
        public Nullable<System.DateTime> joined_date { get; set; }
        public string emp_oth_email { get; set; }
        public Nullable<int> termination_id { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string emp_about { get; set; }
        public string user_id { get; set; }
        public Nullable<int> active { get; set; }
        public int deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_announcement> admin_announcement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_basicsalary> admin_hrm_emp_basicsalary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_dependents> admin_hrm_emp_dependents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_education> admin_hrm_emp_education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_emergency_contacts> admin_hrm_emp_emergency_contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_file> admin_hrm_emp_file { get; set; }
        public virtual admin_hrm_emp_job_record admin_hrm_emp_job_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_job_record_history> admin_hrm_emp_job_record_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_job_record_history> admin_hrm_emp_job_record_history1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_language> admin_hrm_emp_language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_locations> admin_hrm_emp_locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_member_detail> admin_hrm_emp_member_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_reportto> admin_hrm_emp_reportto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_reportto> admin_hrm_emp_reportto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_skill> admin_hrm_emp_skill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_work_experience> admin_hrm_emp_work_experience { get; set; }
        public virtual admin_hrm_lkup_employment_status admin_hrm_lkup_employment_status { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_leave> admin_hrm_leave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_leave_entitlement> admin_hrm_leave_entitlement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_leave_request> admin_hrm_leave_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_suggestion_admin> admin_hrm_suggestion_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_suggestion> admin_hrm_suggestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_timesheet_action_log> admin_hrm_timesheet_action_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_timesheet> admin_hrm_timesheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_timesheet_item> admin_hrm_timesheet_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_activity_admin> pm_activity_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_activity_budget> pm_activity_budget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_activity_budget> pm_activity_budget1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_activity_deliverables> pm_activity_deliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_activity_deliverables> pm_activity_deliverables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_activity_files> pm_activity_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_activity_files> pm_activity_files1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_objective_admin> pm_objective_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_objective_deliverables> pm_objective_deliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_objective_deliverables> pm_objective_deliverables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_objective_files> pm_objective_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_objective_files> pm_objective_files1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_project_admin> pm_project_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_project_deliverables> pm_project_deliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_project_deliverables> pm_project_deliverables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_project_files> pm_project_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_project_files> pm_project_files1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_task_admin> pm_task_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_task_deliverables> pm_task_deliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_task_deliverables> pm_task_deliverables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_task_files> pm_task_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_task_files> pm_task_files1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ws_complain_admin> ws_complain_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ws_notification> ws_notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_admin> product_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Override> Overrides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phone> Phones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Email> User_Email { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<collection_register> collection_register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests { get; set; }
    }
}
