//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hrm_lkup_subunit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin_hrm_lkup_subunit()
        {
            this.admin_hrm_emp_job_record = new HashSet<admin_hrm_emp_job_record>();
            this.admin_hrm_lk_directorate_subunit = new HashSet<admin_hrm_lk_directorate_subunit>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string unit_id { get; set; }
        public string description { get; set; }
        public Nullable<int> lft { get; set; }
        public Nullable<int> rgt { get; set; }
        public Nullable<int> level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_emp_job_record> admin_hrm_emp_job_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hrm_lk_directorate_subunit> admin_hrm_lk_directorate_subunit { get; set; }
    }
}
