//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amenity1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Amenity1()
        {
            this.RoomReservations = new HashSet<RoomReservation>();
        }
    
        public int Amenities_id { get; set; }
        public string Amenities_name { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> room_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservation> RoomReservations { get; set; }
    }
}
