//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetPermission()
        {
            this.AspNetRolePermissions = new HashSet<AspNetRolePermission>();
        }
    
        public int Id { get; set; }
        public string Permission { get; set; }
        public string Section { get; set; }
        public string Module { get; set; }
        public string SubModule { get; set; }
        public string ActionType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRolePermission> AspNetRolePermissions { get; set; }
    }
}
