//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bpm_process
    {
        public System.Guid id { get; set; }
        public string process_name { get; set; }
        public string definition { get; set; }
        public System.DateTime created_at { get; set; }
        public int created_by { get; set; }
        public string version { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public string process_code { get; set; }
        public int status { get; set; }
    }
}
