//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oneportalEntities : DbContext
    {
        public oneportalEntities()
            : base("name=oneportalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<admin_announcement> admin_announcement { get; set; }
        public virtual DbSet<admin_hrm_activity> admin_hrm_activity { get; set; }
        public virtual DbSet<admin_hrm_directorate> admin_hrm_directorate { get; set; }
        public virtual DbSet<admin_hrm_education> admin_hrm_education { get; set; }
        public virtual DbSet<admin_hrm_emp_basicsalary> admin_hrm_emp_basicsalary { get; set; }
        public virtual DbSet<admin_hrm_emp_dependents> admin_hrm_emp_dependents { get; set; }
        public virtual DbSet<admin_hrm_emp_education> admin_hrm_emp_education { get; set; }
        public virtual DbSet<admin_hrm_emp_emergency_contacts> admin_hrm_emp_emergency_contacts { get; set; }
        public virtual DbSet<admin_hrm_emp_file> admin_hrm_emp_file { get; set; }
        public virtual DbSet<admin_hrm_emp_job_record> admin_hrm_emp_job_record { get; set; }
        public virtual DbSet<admin_hrm_emp_job_record_history> admin_hrm_emp_job_record_history { get; set; }
        public virtual DbSet<admin_hrm_emp_language> admin_hrm_emp_language { get; set; }
        public virtual DbSet<admin_hrm_emp_locations> admin_hrm_emp_locations { get; set; }
        public virtual DbSet<admin_hrm_emp_member_detail> admin_hrm_emp_member_detail { get; set; }
        public virtual DbSet<admin_hrm_emp_reportto> admin_hrm_emp_reportto { get; set; }
        public virtual DbSet<admin_hrm_emp_skill> admin_hrm_emp_skill { get; set; }
        public virtual DbSet<admin_hrm_emp_work_experience> admin_hrm_emp_work_experience { get; set; }
        public virtual DbSet<admin_hrm_employee> admin_hrm_employee { get; set; }
        public virtual DbSet<admin_hrm_holiday> admin_hrm_holiday { get; set; }
        public virtual DbSet<admin_hrm_leave> admin_hrm_leave { get; set; }
        public virtual DbSet<admin_hrm_leave_entitlement> admin_hrm_leave_entitlement { get; set; }
        public virtual DbSet<admin_hrm_leave_entitlement_type> admin_hrm_leave_entitlement_type { get; set; }
        public virtual DbSet<admin_hrm_leave_request> admin_hrm_leave_request { get; set; }
        public virtual DbSet<admin_hrm_leave_request_comment> admin_hrm_leave_request_comment { get; set; }
        public virtual DbSet<admin_hrm_leave_status> admin_hrm_leave_status { get; set; }
        public virtual DbSet<admin_hrm_leave_type> admin_hrm_leave_type { get; set; }
        public virtual DbSet<admin_hrm_lk_directorate_subunit> admin_hrm_lk_directorate_subunit { get; set; }
        public virtual DbSet<admin_hrm_lkup_employment_status> admin_hrm_lkup_employment_status { get; set; }
        public virtual DbSet<admin_hrm_lkup_job_title> admin_hrm_lkup_job_title { get; set; }
        public virtual DbSet<admin_hrm_lkup_subunit> admin_hrm_lkup_subunit { get; set; }
        public virtual DbSet<admin_hrm_location> admin_hrm_location { get; set; }
        public virtual DbSet<admin_hrm_suggestion> admin_hrm_suggestion { get; set; }
        public virtual DbSet<admin_hrm_suggestion_files> admin_hrm_suggestion_files { get; set; }
        public virtual DbSet<admin_hrm_timesheet> admin_hrm_timesheet { get; set; }
        public virtual DbSet<admin_hrm_timesheet_action_log> admin_hrm_timesheet_action_log { get; set; }
        public virtual DbSet<admin_hrm_timesheet_item> admin_hrm_timesheet_item { get; set; }
        public virtual DbSet<admin_hrm_timesheet_lk_project_activity> admin_hrm_timesheet_lk_project_activity { get; set; }
        public virtual DbSet<admin_hrm_uploaded_document> admin_hrm_uploaded_document { get; set; }
        public virtual DbSet<AspNetPermission> AspNetPermissions { get; set; }
        public virtual DbSet<AspNetRolePermission> AspNetRolePermissions { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<pm_activity_admin> pm_activity_admin { get; set; }
        public virtual DbSet<pm_activity_budget> pm_activity_budget { get; set; }
        public virtual DbSet<pm_activity_deliverables> pm_activity_deliverables { get; set; }
        public virtual DbSet<pm_activity_files> pm_activity_files { get; set; }
        public virtual DbSet<pm_budget_item> pm_budget_item { get; set; }
        public virtual DbSet<pm_comment> pm_comment { get; set; }
        public virtual DbSet<pm_funder> pm_funder { get; set; }
        public virtual DbSet<pm_objective_admin> pm_objective_admin { get; set; }
        public virtual DbSet<pm_objective_deliverables> pm_objective_deliverables { get; set; }
        public virtual DbSet<pm_objective_files> pm_objective_files { get; set; }
        public virtual DbSet<pm_project> pm_project { get; set; }
        public virtual DbSet<pm_project_admin> pm_project_admin { get; set; }
        public virtual DbSet<pm_project_deliverables> pm_project_deliverables { get; set; }
        public virtual DbSet<pm_project_files> pm_project_files { get; set; }
        public virtual DbSet<pm_project_funding_period> pm_project_funding_period { get; set; }
        public virtual DbSet<pm_project_objective_activity> pm_project_objective_activity { get; set; }
        public virtual DbSet<pm_project_strategic_objective> pm_project_strategic_objective { get; set; }
        public virtual DbSet<pm_project_task> pm_project_task { get; set; }
        public virtual DbSet<pm_task_admin> pm_task_admin { get; set; }
        public virtual DbSet<pm_task_deliverables> pm_task_deliverables { get; set; }
        public virtual DbSet<pm_task_files> pm_task_files { get; set; }
        public virtual DbSet<ws_app_settings> ws_app_settings { get; set; }
        public virtual DbSet<ws_complain> ws_complain { get; set; }
        public virtual DbSet<ws_complain_admin> ws_complain_admin { get; set; }
        public virtual DbSet<ws_complain_files> ws_complain_files { get; set; }
        public virtual DbSet<ws_email_template> ws_email_template { get; set; }
        public virtual DbSet<ws_lookup> ws_lookup { get; set; }
        public virtual DbSet<ws_notification> ws_notification { get; set; }
        public virtual DbSet<admin_hrm_suggestion_admin> admin_hrm_suggestion_admin { get; set; }
        public virtual DbSet<bpm_approval_token> bpm_approval_token { get; set; }
        public virtual DbSet<bpm_employee_signature> bpm_employee_signature { get; set; }
        public virtual DbSet<bpm_form_design> bpm_form_design { get; set; }
        public virtual DbSet<bpm_link_travel_expense> bpm_link_travel_expense { get; set; }
        public virtual DbSet<bpm_lnk_vendor_category> bpm_lnk_vendor_category { get; set; }
        public virtual DbSet<bpm_payments> bpm_payments { get; set; }
        public virtual DbSet<bpm_process> bpm_process { get; set; }
        public virtual DbSet<bpm_transaction_token> bpm_transaction_token { get; set; }
        public virtual DbSet<bpm_travel_expenses> bpm_travel_expenses { get; set; }
        public virtual DbSet<bpm_travel_type> bpm_travel_type { get; set; }
        public virtual DbSet<bpm_vendor> bpm_vendor { get; set; }
        public virtual DbSet<bpm_vendor_category> bpm_vendor_category { get; set; }
        public virtual DbSet<bpm_vendor_document> bpm_vendor_document { get; set; }
        public virtual DbSet<bpm_workflow> bpm_workflow { get; set; }
        public virtual DbSet<bpm_workflow_document> bpm_workflow_document { get; set; }
        public virtual DbSet<bpm_workflow_employee> bpm_workflow_employee { get; set; }
        public virtual DbSet<bpm_workflow_program_approval> bpm_workflow_program_approval { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<laundry_services> laundry_services { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_admin> product_admin { get; set; }
        public virtual DbSet<product_category> product_category { get; set; }
        public virtual DbSet<product_files> product_files { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<AddOn> AddOns { get; set; }
        public virtual DbSet<AddOnRate> AddOnRates { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<Amenity> Amenities { get; set; }
        public virtual DbSet<AmenityRate> AmenityRates { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<CityZip> CityZips { get; set; }
        public virtual DbSet<EmailType> EmailTypes { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Override> Overrides { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<PhoneType> PhoneTypes { get; set; }
        public virtual DbSet<pricing> pricings { get; set; }
        public virtual DbSet<Promo> Promoes { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<ReservationDetail> ReservationDetails { get; set; }
        public virtual DbSet<RoomAmenity> RoomAmenities { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<billing> billings { get; set; }
        public virtual DbSet<User_Email> User_Email { get; set; }
        public virtual DbSet<delivery> deliveries { get; set; }
        public virtual DbSet<collection_register> collection_register { get; set; }
        public virtual DbSet<entry_information> entry_information { get; set; }
        public virtual DbSet<Amenity1> Amenity1 { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomRate> RoomRates { get; set; }
        public virtual DbSet<RoomReservation> RoomReservations { get; set; }
        public virtual DbSet<RoomReservationAddOn> RoomReservationAddOns { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
    }
}
