//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Override
    {
        public int OverrideID { get; set; }
        public int Reservation_ReservationID { get; set; }
        public int Amount { get; set; }
        public string Reason { get; set; }
        public int Employee_EmployeeNumber { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
