//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phone()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int PhoneID { get; set; }
        public int PhoneType_PhoneTypeID { get; set; }
        public string PhoneNumber { get; set; }
        public int Guest_GuestID { get; set; }
        public int Hotel_HotelID { get; set; }
        public int Employee_EmployeeNumber { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual PhoneType PhoneType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
