//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_activity_budget
    {
        public int id { get; set; }
        public int budget_item_id { get; set; }
        public int activity_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime created_at { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> updated_by { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual admin_hrm_employee admin_hrm_employee1 { get; set; }
        public virtual pm_budget_item pm_budget_item { get; set; }
        public virtual pm_project_objective_activity pm_project_objective_activity { get; set; }
    }
}
