//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_comment
    {
        public int id { get; set; }
        public string comment { get; set; }
        public string module { get; set; }
        public int item_id { get; set; }
        public int category { get; set; }
    }
}
