//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_objective_files
    {
        public int id { get; set; }
        public string file_name { get; set; }
        public string file_type { get; set; }
        public System.DateTime uploaded_at { get; set; }
        public int uploaded_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public int processed { get; set; }
        public string file_size { get; set; }
        public int objective_id { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
        public virtual admin_hrm_employee admin_hrm_employee1 { get; set; }
        public virtual pm_project_strategic_objective pm_project_strategic_objective { get; set; }
    }
}
