//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_project_strategic_objective
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pm_project_strategic_objective()
        {
            this.pm_objective_admin = new HashSet<pm_objective_admin>();
            this.pm_objective_deliverables = new HashSet<pm_objective_deliverables>();
            this.pm_objective_files = new HashSet<pm_objective_files>();
            this.pm_project_objective_activity = new HashSet<pm_project_objective_activity>();
        }
    
        public int id { get; set; }
        public string objectve { get; set; }
        public Nullable<int> project_id { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string num { get; set; }
        public int deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_objective_admin> pm_objective_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_objective_deliverables> pm_objective_deliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_objective_files> pm_objective_files { get; set; }
        public virtual pm_project pm_project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_project_objective_activity> pm_project_objective_activity { get; set; }
    }
}
