//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_project_funding_period
    {
        public int id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> funder_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string description { get; set; }
    
        public virtual pm_funder pm_funder { get; set; }
        public virtual pm_project pm_project { get; set; }
    }
}
