//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_project_task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pm_project_task()
        {
            this.pm_task_admin = new HashSet<pm_task_admin>();
            this.pm_task_deliverables = new HashSet<pm_task_deliverables>();
            this.pm_task_files = new HashSet<pm_task_files>();
        }
    
        public int id { get; set; }
        public Nullable<int> objective_activity_id { get; set; }
        public string task { get; set; }
        public string task_type { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> expected_start_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> status { get; set; }
        public string comment { get; set; }
        public int deleted { get; set; }
    
        public virtual pm_project_objective_activity pm_project_objective_activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_task_admin> pm_task_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_task_deliverables> pm_task_deliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_task_files> pm_task_files { get; set; }
    }
}
