//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pricing()
        {
            this.billings = new HashSet<billing>();
        }
    
        public int id { get; set; }
        public string clotheType { get; set; }
        public string washing_price { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string ClothName { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billing> billings { get; set; }
    }
}
