//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_admin
    {
        public int Id { get; set; }
        public string Product_category { get; set; }
        public string Product_type { get; set; }
        public int emp_number { get; set; }
        public int active { get; set; }
    
        public virtual admin_hrm_employee admin_hrm_employee { get; set; }
    }
}
