//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promo()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int PromoID { get; set; }
        public string PromoCode { get; set; }
        public string Description { get; set; }
        public int CurrencyDiscount { get; set; }
        public int PercentDiscount { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int RoomType_RoomTypeID { get; set; }
        public int Amenity_AmenityID { get; set; }
        public int AddOn_AddOnID { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        public virtual Amenity Amenity { get; set; }
        public virtual RoomType RoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
