//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationDetail
    {
        public int ReservationDetailID { get; set; }
        public int Reservation_ReservationID { get; set; }
        public int RoomReservation_RoomReservationID { get; set; }
        public int RoomReservationAddOn_RoomReservationAddOnID { get; set; }
        public string Description { get; set; }
        public decimal Rate { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual RoomReservation RoomReservation { get; set; }
        public virtual RoomReservationAddOn RoomReservationAddOn { get; set; }
    }
}
