//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomReservation()
        {
            this.ReservationDetails = new HashSet<ReservationDetail>();
            this.RoomReservationAddOns = new HashSet<RoomReservationAddOn>();
            this.Guests = new HashSet<Guest>();
        }
    
        public int RoomReservationID { get; set; }
        public Nullable<int> Room_RoomID { get; set; }
        public Nullable<int> Reservation_ReservationID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Room_rate_id { get; set; }
        public Nullable<int> Guest_id { get; set; }
        public Nullable<System.DateTime> CheckinTime { get; set; }
        public Nullable<System.DateTime> CheckoutTime { get; set; }
        public Nullable<decimal> Total_price { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Addon_id { get; set; }
        public Nullable<int> Amenities_id { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        public virtual Amenity1 Amenity { get; set; }
        public virtual Reservation Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationDetail> ReservationDetails { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservationAddOn> RoomReservationAddOns { get; set; }
        public virtual RoomReservation RoomReservation1 { get; set; }
        public virtual RoomReservation RoomReservation2 { get; set; }
        public virtual Guest Guest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests { get; set; }
    }
}
