//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomRate()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int RoomRateID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RoomType_RoomTypeID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Room_name { get; set; }
        public string Room_Description { get; set; }
        public string Available { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
