//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReservationAddOn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomReservationAddOn()
        {
            this.ReservationDetails = new HashSet<ReservationDetail>();
        }
    
        public int RoomReservationAddOnID { get; set; }
        public int RoomReservation_RoomReservationID { get; set; }
        public int AddOn_AddOnID { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationDetail> ReservationDetails { get; set; }
        public virtual RoomReservation RoomReservation { get; set; }
    }
}
