//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.RoomAmenities = new HashSet<RoomAmenity>();
            this.RoomReservations = new HashSet<RoomReservation>();
        }
    
        public int RoomID { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> OccupancyLimit { get; set; }
        public Nullable<int> RoomType_RoomTypeID { get; set; }
        public Nullable<int> Hotel_HotelID { get; set; }
        public Nullable<int> Rome_Rate_id { get; set; }
        public Nullable<int> Amenities_id { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Deleted { get; set; }
        public string Available { get; set; }
        public Nullable<int> phone_id { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual RoomType RoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomAmenity> RoomAmenities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservation> RoomReservations { get; set; }
        public virtual RoomRate RoomRate { get; set; }
    }
}
