//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public int delivery_id { get; set; }
        public int billing_id { get; set; }
        public int order_reg_id { get; set; }
        public int Deleted { get; set; }
    }
}
