//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_complain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ws_complain()
        {
            this.ws_complain_files = new HashSet<ws_complain_files>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Comment { get; set; }
        public string UserId { get; set; }
        public string Priority { get; set; }
        public string Resolved { get; set; }
        public Nullable<System.DateTime> ResolutionDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int Deleted { get; set; }
        public string ResolvedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ws_complain_files> ws_complain_files { get; set; }
    }
}
