//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_email_template
    {
        public int id { get; set; }
        public string name { get; set; }
        public string template { get; set; }
        public string version { get; set; }
        public int deleted { get; set; }
    }
}
