//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_lookup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ws_lookup()
        {
            this.pm_activity_deliverables = new HashSet<pm_activity_deliverables>();
            this.pm_activity_deliverables1 = new HashSet<pm_activity_deliverables>();
            this.pm_objective_deliverables = new HashSet<pm_objective_deliverables>();
            this.pm_objective_deliverables1 = new HashSet<pm_objective_deliverables>();
            this.pm_project_deliverables = new HashSet<pm_project_deliverables>();
            this.pm_project_deliverables1 = new HashSet<pm_project_deliverables>();
            this.pm_task_deliverables = new HashSet<pm_task_deliverables>();
            this.pm_task_deliverables1 = new HashSet<pm_task_deliverables>();
        }
    
        public int id { get; set; }
        public string lookup_name { get; set; }
        public Nullable<int> orderd { get; set; }
        public string category { get; set; }
        public Nullable<int> deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_activity_deliverables> pm_activity_deliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_activity_deliverables> pm_activity_deliverables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_objective_deliverables> pm_objective_deliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_objective_deliverables> pm_objective_deliverables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_project_deliverables> pm_project_deliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_project_deliverables> pm_project_deliverables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_task_deliverables> pm_task_deliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pm_task_deliverables> pm_task_deliverables1 { get; set; }
    }
}
